upgrading to Openshift v1.2.0 and latest Fedora 23

diff --git a/openshift-sdn-ovs b/openshift-sdn-ovs
--- a/openshift-sdn-ovs
+++ b/openshift-sdn-ovs
@@ -6,6 +6,9 @@ lock_file=/var/lock/openshift-sdn.lock
 action=$1
 net_container=$2
 tenant_id=$3
+ingress_bw=$4
+egress_bw=$5
+macvlan=$6
 
 lockwrap() {
     (
@@ -76,6 +79,19 @@ add_ovs_flows() {
 	ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, reg0=0, ip, nw_dst=${ipaddr}, actions=output:${ovs_port}"
 	ovs-ofctl -O OpenFlow13 add-flow br0 "table=7, priority=100, reg0=${tenant_id}, ip, nw_dst=${ipaddr}, actions=output:${ovs_port}"
     fi
+
+    # Pod ingress == OVS bridge egress
+    # linux-htb used here since that's the Kubernetes default traffic shaper too
+    if [ -n "${ingress_bw}" ]; then
+        qos=$(ovs-vsctl create qos type=linux-htb other-config:max-rate=${ingress_bw})
+        ovs-vsctl set port ${veth_host} qos=${qos}
+    fi
+
+    # Pod egress == OVS bridge ingress
+    if [ -n "${egress_bw}" ]; then
+        # OVS ingress_policing specified in Kbps
+        ovs-vsctl set interface ${veth_host} ingress_policing_rate=$((${egress_bw}/1000))
+    fi
 }
 
 del_ovs_flows() {
@@ -83,6 +99,12 @@ del_ovs_flows() {
     ovs-ofctl -O OpenFlow13 del-flows br0 "ip,nw_src=${ipaddr}"
     ovs-ofctl -O OpenFlow13 del-flows br0 "arp,nw_dst=${ipaddr}"
     ovs-ofctl -O OpenFlow13 del-flows br0 "arp,nw_src=${ipaddr}"
+
+    qos=$(ovs-vsctl get port ${veth_host} qos)
+    if [ "$qos" != "[]" ]; then
+        ovs-vsctl clear port ${veth_host} qos
+        ovs-vsctl --if-exists destroy qos ${qos}
+    fi
 }
 
 add_subnet_route() {
@@ -94,6 +116,16 @@ ensure_subnet_route() {
     add_subnet_route
 }
 
+add_macvlan() {
+    default_dev=$(ip route show | sed -ne 's/^default .* dev \([^ ]*\) .*/\1/p')
+    if [ -z "$default_dev" ]; then
+	echo "Could not find default network interface"
+	exit 1
+    fi
+    ip link add link $default_dev name macvlan0 type macvlan mode private
+    ip link set macvlan0 netns $pid
+}
+
 run() {
     get_ipaddr_pid_veth
     source /run/openshift-sdn/config.env
@@ -103,6 +135,9 @@ run() {
 	    add_ovs_port
 	    add_ovs_flows
 	    add_subnet_route
+	    if [ "$macvlan" = true ]; then
+		add_macvlan
+	    fi
 	    ;;
 
 	update)
@@ -113,8 +148,9 @@ run() {
 	    ;;
 
 	teardown)
-	    del_ovs_port
 	    del_ovs_flows
+	    # Delete ovs port in the end, del_ovs_flows needs the port to delete qos record
+	    del_ovs_port
 	    ;;
 
 	*)
